server:
  port: 1234

spring:
  zipkin:
    base-url: http://zipkin:9411/
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USER_NAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://postgres:5432/postgres}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ms-inventory

keycloak:
  auth-server-url: http://172.18.5.38:8081
  autodetect-bearer-only: true
  credentials:
    secret: tCDIWn00UTUCJeARVwSvN3mAOPewdxBX
  realm: ms-software
  resource: backend
  ssl-required: none
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - ADMIN
      security-collections:
        - name: SERVICIOS DE ADMINISTRADOR
          omitted-methods:
            - OPTIONS
          patterns:
            - /api/v1/product/register
            - /api/v1/product/update
            - /api/v1/product/delete
            - /api/v1/product/all
            - /api/v1/product/getById
            - /api/v1/minio/upload
            -

eureka:
    client:
      registerWithEureka: true
      serviceUrl:
        defaultZone: ${DISCOVERY_URL:http://ms-discovery:8701/eureka/}

#minio:
#  access-key: ${MINIO_AK:eOVCfYh7WDgRp6q5rZuh}
#  secret-key: ${MINIO_SK:V0tYbqTwpt8fWGhJo3CfadyweWCm0Vi0VF44RRZ5}
#  url: ${MINIO_URL:http://172.18.5.38:9001}
#  bucket: ${MINIO_BUCKET:logssoftware}

resilience4j:
  circuitbreaker:
    instances:
      userCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 10
        maxWaitDuration: 2000
    instances:
      userBH:
        baseConfig: default
  ratelimiter:
    configs:
      default:
        limitRefreshPeriod: 10s
        limitForPeriod: 10
    instances:
      userRL:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
    instances:
      userRT:
        baseConfig: default

management:
  endpoints:
    web:
    exposure:
      include: "*"

  endpoint:
    health:
      circuit-breakers:
        enabled: true


