server:
  port: 1234

spring:
  application:
    name: ms-inventory

eureka:
    client:
      registerWithEureka: true
      serviceUrl:
        defaultZone: ${DISCOVERY_URL:http://localhost:8701/eureka/}

