server:
  port: 1234

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USER_NAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://localhost:5432/postgres}
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ms-inventory

eureka:
    client:
      registerWithEureka: false
      serviceUrl:
        defaultZone: ${DISCOVERY_URL:http://localhost:8701/eureka/}

